apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: northwind
data:
  # root password is required to be specified
  ROOT_PASSWORD: Y2hhbmdlaXQ=
  ## application credentials that will be created at cluster bootstrap
  # DATABASE:
  # USER:
  # PASSWORD:
