---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-po
  namespace: fortune-ns
  labels:
    app: fortune

spec:
  containers:
    - name: fortune-container
      image: piksinthen/my-fortune:v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
