---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nwapp-config
  labels:
    app: northwind
data:
  DB_HOST: nwdb-svc.nw.svc.cluster.local # if same namespace, shorthand: nwdb-svc, FQDN (Fully Qualified Domain Name): nwdb-svc.northwind.svc.cluster.local
  DB_USER: root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: northwind

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nwapp-pod
  template:
    metadata:
      name: nwapp-pod
      labels:
        app: nwapp-pod
    spec:
      containers:
        - name: nwapp-container
          image: piksinthen/my-server:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nw-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: nwapp-config
          ports:
            - name: nwapp-port
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
  labels:
    app: northwind

spec:
  type: LoadBalancer
  selector:
    app: nwapp-pod
  ports:
    - name: nwapp-svc-port
      port: 80
      targetPort: nwapp-port
