---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: wpdb-cluster-mysql.wp-ns.svc.cluster.local # if same namespace, shorthand: nwdb-svc, FQDN (Fully Qualified Domain Name): nwdb-svc.wordpress.svc.cluster.local
  WORDPRESS_DB_USER: root

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpcontent-pvc
  labels:
    app: wordpress
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      # G - 1000MB, Gi - 1024MB
      storage: 1Gi
  volumeMode: Filesystem

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wordpress

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: wp-pod
      labels:
        app: wp-pod
    spec:
      volumes:
        - name: wpcontent-vol
          persistentVolumeClaim:
            claimName: wpcontent-pvc
      containers:
        - name: wp-container
          image: wordpress:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wpdb-secret
                  key: ROOT_PASSWORD
            # - name: INSTANCE_IP_ADDRESS
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: wp-config
          ports:
            - name: wp-port
              containerPort: 80
          volumeMounts:
            - name: wpcontent-vol
              mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
  name: wpapp-svc
  labels:
    app: wordpress

spec:
  type: ClusterIP
  selector:
    app: wpapp-pod
  ports:
    - name: wpapp-svc-port
      port: 80
      targetPort: wpapp-port

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wpapp-ing
  labels:
    app: wordpress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  ingressClassName: nginx
  rules:
    - host: acme.139.59.223.108.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: wpapp-svc
              servicePort: wpapp-svc-port
